# Generated by Django 4.0.4 on 2022-05-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='fname')),
                ('last_name', models.CharField(max_length=100, verbose_name='lname')),
                ('age', models.PositiveIntegerField()),
                ('birthday', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
