# Generated by Django 4.0.4 on 2022-05-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
