# Generated by Django 4.0.4 on 2022-07-01 00:15

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='first name')),
                ('last_name', models.CharField(db_column='last_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='last name')),
                ('phone_number', models.CharField(max_length=25, null=True, validators=[core.validators.phone_number_validator])),
                ('speciality', models.CharField(max_length=50)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.group')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
