# Generated by Django 4.0.4 on 2022-06-30 13:17

from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[teachers.validators.phone_number_validator]),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
