# Generated by Django 4.0.4 on 2022-07-01 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name')),
                ('educational_direction', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='educational direction')),
                ('count_disciplines', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='count disciplines')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
