# Generated by Django 4.0.4 on 2022-07-01 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number_of_lessons', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
